apiVersion: v1
kind: Service
metadata:
  name: letters
  namespace: letters
spec:
  type: NodePort
  ports:
  - port: 5230
    targetPort: 5230
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: letters